component_depth: 2
languages:
- name: cpp
  production:
    exclude:
    - .*/CalculatorUnitTests/.*\.cpp
    - .*/internal/.*\.cp
  test:
    include:
      - .*/CalculatorUnitTests/.*\.cpp
      - .*/internal/.*\.cpp
